"""Markdown report generator.

Creates a self-contained Markdown report embedding SVG charts
and summary statistics from the results CSV.
"""

import os


def generate_report(results_csv: str,
                    jobs_csv: str,
                    baseline: str,
                    crux: str,
                    chart_names: list,
                    out_dir: str):
    """Generate vis_report.md in out_dir, embedding generated SVGs."""

    # Read scheduler-level results
    import pandas as pd
    results = pd.read_csv(results_csv)
    b_row = results[results["scheduler"] == baseline]
    c_row = results[results["scheduler"] == crux]

    lines = []
    lines.append("# Crux/SimGrid Visualization Report")
    lines.append("")
    lines.append(f"**Baseline**: `{baseline}` | **Crux**: `{crux}`")
    lines.append("")

    # ── Summary table ────────────────────────────────────────────
    lines.append("## 1. Scheduler Comparison")
    lines.append("")
    lines.append("| Scheduler | Makespan (s) | Avg JCT (s) | Avg Comm (s) | Useful GPU Fraction |")
    lines.append("|---:|---:|---:|---:|---:|")
    for _, row in results.iterrows():
        lines.append(
            f"| `{row['scheduler']}` "
            f"| {row['makespan_s']:.3f} "
            f"| {row['avg_jct_s']:.3f} "
            f"| {row['avg_comm_s']:.3f} "
            f"| {row['useful_gpu_fraction']:.4f} |"
        )

    if not b_row.empty and not c_row.empty:
        b = b_row.iloc[0]
        c = c_row.iloc[0]
        ms_gain = (b["makespan_s"] - c["makespan_s"]) / b["makespan_s"] * 100
        jct_gain = (b["avg_jct_s"] - c["avg_jct_s"]) / b["avg_jct_s"] * 100
        comm_gain = (b["avg_comm_s"] - c["avg_comm_s"]) / b["avg_comm_s"] * 100

        lines.append("")
        lines.append("### Gains vs baseline")
        lines.append("")
        lines.append(f"- Makespan: **{ms_gain:+.2f}%**")
        lines.append(f"- Avg JCT: **{jct_gain:+.2f}%**")
        lines.append(f"- Avg Comm: **{comm_gain:+.2f}%**")

    lines.append("")

    # ── Charts ───────────────────────────────────────────────────
    lines.append("## 2. Charts")
    lines.append("")

    svg_map = {
        "gantt_comparison":             ("Job Timeline (Gantt)",           "Job Gantt comparison: baseline vs crux"),
        "placement_heatmap":            ("GPU Placement",                  "GPU slot occupancy per host"),
        "job_jct_comm_comparison":      ("Per-Job JCT & Comm Comparison",  "JCT and communication time per job"),
        "topology_diagram":             ("Network Topology",               "Static network topology diagram"),
        "intensity_distribution":       ("Communication Intensity",        "Job intensity distribution"),
        "path_switch_heatmap":          ("Switch Path Distribution",       "Cross-host flows through switches"),
    }

    for name in chart_names:
        if name in svg_map:
            title, desc = svg_map[name]
            lines.append(f"### {title}")
            lines.append("")
            lines.append(f"![{desc}]({name}.svg)")
            lines.append("")

    # ── Footer ───────────────────────────────────────────────────
    lines.append("---")
    lines.append("")
    lines.append("*Generated by vis/vis_main.py — Crux/SimGrid Visualization Phase 1*")

    report_path = os.path.join(out_dir, "vis_report.md")
    with open(report_path, "w") as f:
        f.write("\n".join(lines))
    print(f"  report: {report_path}")
